---
tiers:
    -
        name: simple
        order: 0
        description: ''
        testcases:
            -
                case_name: validateLinuxDistribution
                project_name: sylva
                criteria: 1
                blocking: false
                clean_flag: false
                description: ''
                run:
                    name: sylva
                    args:
                        test: validateLinuxDistribution
                        debug: true
            -
                case_name: validateKubernetesAPIs
                project_name: sylva
                criteria: 1
                blocking: false
                clean_flag: false
                description: ''
                run:
                    name: sylva
                    args:
                        test: validateKubernetesAPIs
                        debug: true
            -
                case_name: validateLinuxKernelVersion
                project_name: sylva
                criteria: 1
                blocking: false
                clean_flag: false
                description: ''
                run:
                    name: sylva
                    args:
                        test: validateLinuxKernelVersion
                        debug: true
            -
                case_name: validateAnuketProfileLabels
                project_name: sylva
                criteria: 1
                blocking: false
                clean_flag: false
                description: ''
                run:
                    name: sylva
                    args:
                        test: validateAnuketProfileLabels
                        debug: true
            -
                case_name: validateSMT
                project_name: sylva
                criteria: 1
                blocking: false
                clean_flag: false
                description: ''
                run:
                    name: sylva
                    args:
                        test: validateSMT
                        debug: true
            -
                case_name: validatePhysicalStorage
                project_name: sylva
                criteria: 1
                blocking: false
                clean_flag: false
                description: ''
                run:
                    name: sylva
                    args:
                        test: validatePhysicalStorage
                        debug: true
            -
                case_name: validateStorageQuantity
                project_name: sylva
                criteria: 1
                blocking: false
                clean_flag: false
                description: ''
                run:
                    name: sylva
                    args:
                        test: validateStorageQuantity
                        debug: true
            -
                case_name: validateVcpuQuantity
                project_name: sylva
                criteria: 1
                blocking: false
                clean_flag: false
                description: ''
                run:
                    name: sylva
                    args:
                        test: validateVcpuQuantity
                        debug: true
            -
                case_name: validateCPUPinning
                project_name: sylva
                criteria: 1
                blocking: false
                clean_flag: false
                description: ''
                run:
                    name: sylva
                    args:
                        test: validateCPUPinning
                        debug: true
            -
                case_name: validateNFD
                project_name: sylva
                criteria: 1
                blocking: false
                clean_flag: false
                description: ''
                run:
                    name: sylva
                    args:
                        test: validateNFD
                        debug: true
            -
                case_name: validateSystemResourceReservation
                project_name: sylva
                criteria: 1
                blocking: false
                clean_flag: false
                description: ''
                run:
                    name: sylva
                    args:
                        test: validateSystemResourceReservation
                        debug: true
            -
                case_name: validateHugepages
                project_name: sylva
                criteria: 1
                blocking: false
                clean_flag: false
                description: ''
                run:
                    name: sylva
                    args:
                        test: validateHugepages
                        debug: true
            -
                case_name: validateRT
                project_name: sylva
                criteria: 1
                blocking: false
                clean_flag: false
                description: ''
                run:
                    name: sylva
                    args:
                        test: validateRT
                        debug: true
