---
- hosts: 127.0.0.1
  roles:
    - role: collivier.xtesting
      project: functest-kubernetes
      db_project: functest
      gerrit_project: functest-kubernetes
      docker_tags:
        - v1.21:
            branch: stable/v1.21
      builds:
        dependencies:
          - repo: _
            dport:
            container: alpine
            tag: 3.13
        steps:
          - name: build opnfv/functest-kubernetes-core
            containers:
              - name: functest-kubernetes-core
                ref_arg: BRANCH
                path: docker/core
          - name: build containers
            containers:
              - name: functest-kubernetes-healthcheck
                ref_arg:
                path: docker/healthcheck
              - name: functest-kubernetes-cnf
                ref_arg: BRANCH
                path: docker/cnf
              - name: functest-kubernetes-security
                ref_arg: BRANCH
                path: docker/security
          - name: build opnfv/functest-kubernetes-smoke
            containers:
              - name: functest-kubernetes-smoke
                ref_arg:
                path: docker/smoke
          - name: build opnfv/functest-kubernetes-benchmarking
            containers:
              - name: functest-kubernetes-benchmarking
                ref_arg:
                path: docker/benchmarking
      suites:
        - container: functest-kubernetes-healthcheck
          tests:
            - k8s_quick
            - k8s_smoke
        - container: functest-kubernetes-smoke
          timeout: 3h
          properties:
            execution-type: SEQUENTIALLY
          tests:
            - xrally_kubernetes
            - k8s_conformance
            - k8s_conformance_serial
            - sig_api_machinery
            - sig_api_machinery_serial
            - sig_apps
            - sig_apps_serial
            - sig_auth
            - sig_cluster_lifecycle
            - sig_instrumentation
            - sig_network
            - sig_node
            - sig_scheduling_serial
            - sig_storage
            - sig_storage_serial
        - container: functest-kubernetes-security
          tests:
            - kube_hunter
            - kube_bench_master
            - kube_bench_node
        - container: functest-kubernetes-benchmarking
          tests:
            - xrally_kubernetes_full
            - netperf
        - container: functest-kubernetes-cnf
          tests:
            - k8s_vims
            - helm_vims
            - cnf_testsuite
