apiVersion: apps/v1
kind: Deployment
metadata:
  name: ellis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ellis
  template:
    metadata:
      labels:
        service: ellis
    spec:
      containers:
      - image: "ollivier/clearwater-ellis:latest"
        imagePullPolicy: Always
        name: ellis
        ports:
        - containerPort: 22
        - containerPort: 80
        envFrom:
        - configMapRef:
              name: env-vars
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
        readinessProbe:
          tcpSocket:
            port: 80
      imagePullSecrets:
      - name: ~
      restartPolicy: Always
