apiVersion: batch/v1
kind: Job
metadata:
  name: kube-hunter
spec:
  template:
    spec:
      containers:
      - name: kube-hunter
        image: {{ dockerhub_repo }}/aquasec/kube-hunter:0.6.8
        command: ["kube-hunter"]
        args: ["--pod", "--report", "json", "--statistics"]
      restartPolicy: Never
  backoffLimit: 4
